# Generated by Django 4.2.11 on 2026-02-17 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('responsavel', models.CharField(default='', help_text='Nome do responsável pela equipe', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_proposta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='propostas/')),
                ('quantidade_produtos', models.IntegerField(default=0, help_text='Quantidade de produtos cadastrados na proposta')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('validada', 'Validada'), ('rejeitada', 'Rejeitada'), ('vendida', 'Vendida'), ('nao_vendida', 'Não Vendida')], default='enviada', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('data_venda', models.DateTimeField(blank=True, null=True)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cliente_venda', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade_produtos_venda', models.IntegerField(default=0, help_text='Quantidade de produtos na venda efetuada')),
                ('observacoes_venda', models.TextField(blank=True, null=True)),
                ('venda_validada', models.BooleanField(default=False)),
                ('data_validacao_venda', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao_venda', models.TextField(blank=True, null=True)),
                ('data_rejeicao_venda', models.DateTimeField(blank=True, null=True)),
                ('pontos', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='api.cliente')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='api.equipe')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_validadas', to=settings.AUTH_USER_MODEL)),
                ('venda_validada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_validadas_proposta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores', to='api.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produtos_vendidos', models.IntegerField(default=0)),
                ('valor_total_venda', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_venda', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status_validacao', models.CharField(choices=[('pendente', 'Pendente de Validação'), ('validada', 'Venda Validada'), ('rejeitada', 'Venda Rejeitada')], default='pendente', help_text='Status da validação pelo gestor', max_length=20)),
                ('pontos_gerados', models.IntegerField(default=0, help_text='Pontos calculados para esta venda')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_validacao', models.DateTimeField(blank=True, help_text='Data da validação pelo gestor', null=True)),
                ('proposta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venda', to='api.proposta')),
                ('validado_por', models.ForeignKey(blank=True, help_text='Gestor que validou esta venda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_validadas_gestor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='StatusSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_atual', models.CharField(choices=[('pre_workshop', 'Pré-Workshop'), ('workshop', 'Workshop'), ('pos_workshop', 'Pós-Workshop'), ('encerrado', 'Encerrado')], default='pre_workshop', max_length=20)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status do Sistema',
                'verbose_name_plural': 'Status do Sistema',
            },
        ),
        migrations.CreateModel(
            name='ResultadoPosWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_fechado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_propostas_fechadas', models.IntegerField(default=0)),
                ('linhas_produto_vendidas', models.TextField(help_text='Lista de linhas de produto vendidas')),
                ('faturamento_total_realizado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_fechamento', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.vendedor')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.workshop')),
            ],
            options={
                'verbose_name': 'Resultado Pós-Workshop',
                'verbose_name_plural': 'Resultados Pós-Workshop',
            },
        ),
        migrations.CreateModel(
            name='RegraPontuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('pontos', models.IntegerField()),
                ('tipo', models.CharField(choices=[('proposta_enviada', 'Proposta Enviada'), ('proposta_validada', 'Proposta Validada'), ('venda_concretizada', 'Venda Concretizada'), ('quantidade_produtos', 'Quantidade de Produtos')], max_length=50)),
                ('estado_sistema', models.CharField(choices=[('pre_workshop', 'Pré-Workshop'), ('workshop', 'Workshop'), ('pos_workshop', 'Pós-Workshop'), ('encerrado', 'Encerrado')], default='workshop', help_text='Estado em que esta regra se aplica', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regra de Pontuação',
                'verbose_name_plural': 'Regras de Pontuação',
                'unique_together': {('tipo', 'estado_sistema')},
            },
        ),
        migrations.AddField(
            model_name='proposta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='api.vendedor'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='api.workshop'),
        ),
        migrations.CreateModel(
            name='PrevisaoWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total_previsto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_propostas', models.IntegerField(default=0)),
                ('linhas_produto', models.TextField(help_text='Lista de linhas de produto previstas')),
                ('faturamento_total_previsto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='api.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='api.vendedor')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='api.workshop')),
            ],
            options={
                'verbose_name': 'Previsão de Workshop',
                'verbose_name_plural': 'Previsões de Workshop',
            },
        ),
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('administrador', 'Administrador'), ('gestor', 'Gestor'), ('banca', 'Banca'), ('equipe', 'Equipe')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(blank=True, help_text='Equipe permitida para acesso de nível equipe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipe')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Acesso',
                'verbose_name_plural': 'Perfis de Acesso',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoPontuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_proposta_validada', models.IntegerField(default=0, help_text='Pontos fixos por proposta validada')),
                ('pontos_por_produto', models.IntegerField(default=0, help_text='Pontos por produto (aplica-se tanto a propostas validadas quanto a vendas concretizadas)')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Pontuação',
                'verbose_name_plural': 'Configurações de Pontuação',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='api.vendedor'),
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_sistema', models.CharField(choices=[('pre_workshop', 'Pré-Workshop'), ('workshop', 'Workshop'), ('pos_workshop', 'Pós-Workshop'), ('encerrado', 'Encerrado')], default='workshop', help_text='Estado em que esta regra se aplica', max_length=20)),
                ('posicao', models.IntegerField()),
                ('pontos', models.IntegerField(default=0)),
                ('propostas_enviadas', models.IntegerField(default=0)),
                ('propostas_validadas', models.IntegerField(default=0)),
                ('vendas_concretizadas', models.IntegerField(default=0)),
                ('valor_total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_ranking', to='api.equipe')),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Ranking',
                'ordering': ['estado_sistema', 'posicao'],
                'unique_together': {('equipe', 'estado_sistema')},
            },
        ),
    ]
