# Generated by Django 4.2.11 on 2026-02-09 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='api.regional')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores', to='api.equipe')),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='api.regional')),
            ],
        ),
        migrations.CreateModel(
            name='StatusSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_atual', models.CharField(choices=[('pre_workshop', 'Pré-Workshop'), ('workshop', 'Workshop'), ('pos_workshop', 'Pós-Workshop'), ('encerrado', 'Encerrado')], default='pre_workshop', max_length=20)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status do Sistema',
                'verbose_name_plural': 'Status do Sistema',
            },
        ),
        migrations.CreateModel(
            name='ResultadoPosWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_fechado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_propostas_fechadas', models.IntegerField(default=0)),
                ('linhas_produto_vendidas', models.TextField(help_text='Lista de linhas de produto vendidas')),
                ('faturamento_total_realizado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_fechamento', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.vendedor')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.workshop')),
            ],
            options={
                'verbose_name': 'Resultado Pós-Workshop',
                'verbose_name_plural': 'Resultados Pós-Workshop',
            },
        ),
        migrations.CreateModel(
            name='PrevisaoWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total_previsto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_propostas', models.IntegerField(default=0)),
                ('linhas_produto', models.TextField(help_text='Lista de linhas de produto previstas')),
                ('faturamento_total_previsto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='api.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='api.vendedor')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='api.workshop')),
            ],
            options={
                'verbose_name': 'Previsão de Workshop',
                'verbose_name_plural': 'Previsões de Workshop',
            },
        ),
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('administrador', 'Administrador'), ('gestor', 'Gestor'), ('banca', 'Banca'), ('equipe', 'Equipe')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(blank=True, help_text='Equipe permitida para acesso de nível equipe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipe')),
                ('regional', models.ForeignKey(blank=True, help_text='Regional permitida para acesso de nível gestor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.regional')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Acesso',
                'verbose_name_plural': 'Perfis de Acesso',
            },
        ),
        migrations.AddField(
            model_name='equipe',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='api.regional'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='api.vendedor'),
        ),
    ]
