# Generated by Django 4.2.11 on 2026-02-09 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraPontuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('pontos', models.IntegerField()),
                ('tipo', models.CharField(choices=[('proposta_enviada', 'Proposta Enviada'), ('proposta_validada', 'Proposta Validada'), ('venda_concretizada', 'Venda Concretizada'), ('bonus_equipe', 'Bônus Equipe')], max_length=50)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regra de Pontuação',
                'verbose_name_plural': 'Regras de Pontuação',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField()),
                ('pontos', models.IntegerField(default=0)),
                ('propostas_enviadas', models.IntegerField(default=0)),
                ('propostas_validadas', models.IntegerField(default=0)),
                ('vendas_concretizadas', models.IntegerField(default=0)),
                ('valor_total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_ranking', to='api.equipe')),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Ranking',
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_proposta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.TextField()),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='propostas/')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('validada', 'Validada'), ('rejeitada', 'Rejeitada'), ('vendida', 'Vendida'), ('nao_vendida', 'Não Vendida')], default='enviada', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('data_venda', models.DateTimeField(blank=True, null=True)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('venda_validada', models.BooleanField(default=False)),
                ('data_validacao_venda', models.DateTimeField(blank=True, null=True)),
                ('pontos', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='api.cliente')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='api.equipe')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_validadas', to=settings.AUTH_USER_MODEL)),
                ('venda_validada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_validadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='api.vendedor')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='api.workshop')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-data_envio'],
            },
        ),
    ]
