# Generated by Django 4.2.11 on 2026-02-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='bonus_aceleracao',
            field=models.BooleanField(default=False, verbose_name='Bônus de Aceleração (Venda fechada durante o game)'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='bonus_espumantes_premium',
            field=models.BooleanField(default=False, verbose_name='Linha Espumantes Premium - min de 2 Caixas'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='bonus_espumantes_vintage',
            field=models.BooleanField(default=False, verbose_name='Linha Espumantes Vintage - min de 5 Caixas'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='bonus_vinhos_casa_perini_mundo',
            field=models.BooleanField(default=False, verbose_name='Linha Vinhos Casa Perini Mundo - min 5 Caixas'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='bonus_vinhos_fracao_unica',
            field=models.BooleanField(default=False, verbose_name='Linha Vinhos Fração Única - min de 5 Caixas'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='pontos_bonus',
            field=models.IntegerField(default=0, help_text='Total de pontos extras e de aceleração'),
        ),
    ]
