# Generated by Django 4.2.11 on 2026-02-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proposta_bonus_aceleracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='numero_proposta_equipe',
            field=models.IntegerField(default=0, help_text='Número sequencial da proposta dentro da equipe'),
        ),
    ]
