# Generated by Django 4.2.11 on 2026-02-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_regrapontuacao_ranking_proposta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['estado_sistema', 'posicao'], 'verbose_name': 'Ranking', 'verbose_name_plural': 'Ranking'},
        ),
        migrations.AddField(
            model_name='ranking',
            name='estado_sistema',
            field=models.CharField(choices=[('pre_workshop', 'Pré-Workshop'), ('workshop', 'Workshop'), ('pos_workshop', 'Pós-Workshop'), ('encerrado', 'Encerrado')], default='workshop', help_text='Estado em que esta regra se aplica', max_length=20),
        ),
        migrations.AddField(
            model_name='regrapontuacao',
            name='estado_sistema',
            field=models.CharField(choices=[('pre_workshop', 'Pré-Workshop'), ('workshop', 'Workshop'), ('pos_workshop', 'Pós-Workshop'), ('encerrado', 'Encerrado')], default='workshop', help_text='Estado em que esta regra se aplica', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('equipe', 'estado_sistema')},
        ),
        migrations.AlterUniqueTogether(
            name='regrapontuacao',
            unique_together={('tipo', 'estado_sistema')},
        ),
    ]
