# Generated by Django 4.2.11 on 2026-02-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ranking_options_ranking_estado_sistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='quantidade_produtos',
            field=models.IntegerField(default=0, help_text='Quantidade de produtos cadastrados na proposta'),
        ),
        migrations.AlterField(
            model_name='regrapontuacao',
            name='tipo',
            field=models.CharField(choices=[('proposta_enviada', 'Proposta Enviada'), ('proposta_validada', 'Proposta Validada'), ('venda_concretizada', 'Venda Concretizada'), ('bonus_equipe', 'Bônus Equipe'), ('quantidade_produtos', 'Quantidade de Produtos')], max_length=50),
        ),
    ]
