# Generated by Django 4.2.11 on 2026-02-09 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_proposta_quantidade_produtos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('pontos', models.IntegerField(help_text='Pontos de bônus')),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regra de Bônus',
                'verbose_name_plural': 'Regras de Bônus',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produtos_vendidos', models.IntegerField(default=0)),
                ('valor_total_venda', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_venda', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pontos_gerados', models.IntegerField(default=0, help_text='Pontos calculados para esta venda')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('proposta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venda', to='api.proposta')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoPontuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_proposta_validada', models.IntegerField(default=0, help_text='Pontos por proposta validada')),
                ('pontos_por_produto', models.IntegerField(default=0, help_text='Pontos por produto vendido')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Pontuação',
                'verbose_name_plural': 'Configurações de Pontuação',
            },
        ),
    ]
