# Generated by Django 4.2.11 on 2026-02-09 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_regrabonus_venda_configuracaopontuacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AddField(
            model_name='venda',
            name='data_validacao',
            field=models.DateTimeField(blank=True, help_text='Data da validação pelo gestor', null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='status_validacao',
            field=models.CharField(choices=[('pendente', 'Pendente de Validação'), ('validada', 'Venda Validada'), ('rejeitada', 'Venda Rejeitada')], default='pendente', help_text='Status da validação pelo gestor', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='validado_por',
            field=models.ForeignKey(blank=True, help_text='Gestor que validou esta venda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_validadas_gestor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configuracaopontuacao',
            name='pontos_por_produto',
            field=models.IntegerField(default=0, help_text='Pontos por produto (aplica-se tanto a propostas validadas quanto a vendas concretizadas)'),
        ),
        migrations.AlterField(
            model_name='configuracaopontuacao',
            name='pontos_proposta_validada',
            field=models.IntegerField(default=0, help_text='Pontos fixos por proposta validada'),
        ),
    ]
