# Generated by Django 4.2.11 on 2026-02-09 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_venda_options_venda_data_validacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='venda_validada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_validadas_proposta', to=settings.AUTH_USER_MODEL),
        ),
    ]
