# Generated by Django 4.2.11 on 2026-02-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_proposta_venda_validada_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='cliente_venda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='observacoes_venda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='motivo_rejeicao_venda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposta',
            name='data_rejeicao_venda',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
