# Generated by Django 4.2.11 on 2026-02-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_proposta_campos_venda_pos_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='api.regional'),
        ),
    ]
